### ISSUE TITLE
Updating feed to the same reference fails

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/swarm-actions#38]
See https://github.com/ethersphere/swarm-actions/runs/5522154884?check_suite_focus=true
<img width="1298" alt="Screenshot 2022-03-12 at 16 57 59" src="https://user-images.githubusercontent.com/7974813/158025316-903061c9-e0d2-4280-94cd-eacd9e46421f.png">

**Comment by filoozom** [comment]
It is quite a strange issue though. For example, these runs (and probably some more) were all successful:
- https://github.com/ethersphere/swarm-actions/runs/5541902041
- https://github.com/ethersphere/swarm-actions/runs/5544140590
- https://github.com/ethersphere/swarm-actions/runs/5541457882
- https://github.com/ethersphere/swarm-actions/runs/5529233836

Despite writing the same reference to the feed: `ffdbbdf02eadad4800040b2d6a1a736f4e529ebbddf74a851553ce08e4bfeea3`.

This is the only one that failed: https://github.com/ethersphere/swarm-actions/runs/5535679700

Could that be linked to load-balancing? If so, does it explain everything? I guess there would have to be 4 nodes at the very least in that case?

**Comment by agazso** [comment]
Indeed this can be because of load-balancing. One solution when using a gateway can be to use cookies for make a session stick to a certain node. However that relies on the client storing the cookie and send it in subsequent request at least for a duration of a session. This is automatically the case in the browser but this is not the case in general when using a custom client application.
 
Also writing to the same feed with multiple writers leads to undefined behavior which can manifest in similar errors.
